### ISSUE TITLE
i have an error but i don't understand why i have him

### ISSUE THREAD

**Issue by miyucode** [huskeee/tkvideo#7]
my error are: `Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\rosel\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\rosel\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rosel\AppData\Local\Programs\Python\Python38\lib\site-packages\tkvideo\tkvideo.py", line 51, in load
    label.config(image=frame_image)
  File "C:\Users\rosel\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1637, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\rosel\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1627, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!toplevel.!label"`

someone can help me?

**Comment by Rovetown** [comment]
Maybe this can help you:

[https://www.programmersought.com/article/49772927518/](url)

**Comment by ghost** [comment]
Maybe this will help:

https://www.programmersought.com/article/49772927518/
